apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master-pv
  labels:
    run: jenkins-master
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-33287ac4
    fsType: ext4
