apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-pvc
  labels:
    run: jenkins-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi