apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-svc
  labels:
    run: jenkins-master
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 50000
    protocol: TCP
    name: slave
  selector:
    run: jenkins-master
